language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools

  - build-tools-28.0.3

  - android-28

  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19


before_install:
- yes | sdkmanager "platforms;android-28"
- chmod +x gradlew

branches:
  only:
  - master
  - develop  #  With this script, it will only allow travis to build when there is branch update or pull request to branch master and develop. Depend on your setting at Travis dasshboard

script:
- bash gradlew assembleRelease --info
- find . -iname *.apk

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key: "8466010a56308dc67ff5dce77caeb558797e7546"
  file:
  - Fastlane/app/build/outputs/apk/release/app-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true